# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  ambev.developerevaluation.webapi:
    build:
      context: "C:\\Users\\padra\\Downloads\\testeNTTData\\testeNTTData"
      dockerfile: "src/Ambev.DeveloperEvaluation.WebApi/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Ambev.DeveloperEvaluation.WebApi.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "ambevdeveloperevaluationwebapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\padra\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\padra\\Downloads\\testeNTTData\\testeNTTData\\src\\Ambev.DeveloperEvaluation.WebApi:/app:rw"
    - "C:\\Users\\padra\\Downloads\\testeNTTData\\testeNTTData:/src:rw"
    working_dir: "/app"
